  /chat/getAll:
    get:
      summary: Retrieve a list of chats
      responses:
        200:
          description: A list of chats
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: 1

  /chat/user/{user_id}:
    get:
      summary: Retrieve a list of chats by user ID
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
            example: 1
      responses:
        200:
          description: A list of chats
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: 1
        404:
          description: Chat not found

  /chat/{chat_id}:
    get:
      summary: Retrieve a chat by ID
      parameters:
        - in: path
          name: chat_id
          required: true
          schema:
            type: string
            example: hohno
      responses:
        200:
          description: A chat
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: 1
        404:
          description: Chat not found

  /chat/newChat:
      post:
        summary: Create a new chat
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - user1
                  - user2
                properties:
                  user1:
                    type: string
                    example: 2
                  user2:
                    type: string
                    example: 3
        responses:
          201:
            description: Chat created successfully
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: string
                      example: 1
                    user1:
                      type: string
                      example: 1
                    user2:
                      type: string
                      example: 2
          400:
            description: Invalid input

  /chat/deleteChat:
    delete:
      summary: Delete a chat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: string
                  example: 1
      responses:
        201:
          description: Chat deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 1
                  user1:
                    type: string
                    example: 1
                  user2:
                    type: string
                    example: 2
        400:
          description: Invalid input
