  /chat/getAll:
    get:
      summary: Retrieve a list of chats
      responses:
        200:
          description: A list of chats
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: 1

  /chat/user/{user_id}:
    get:
      summary: Retrieve a list of chats by user ID
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
            example: 1
      responses:
        200:
          description: A list of chats
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: 1
        404:
          description: Chat not found

  /chat/{chat_id}:
    get:
      summary: Retrieve a chat by ID
      parameters:
        - in: path
          name: chat_id
          required: true
          schema:
            type: string
            example: hohno
      responses:
        200:
          description: A chat
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: 1
        404:
          description: Chat not found

